FROM ruby:2.6.3

LABEL maintainer="Borey Lim <lim.borey@gmail.com>"

# Updating nodejs version
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash

RUN apt-get update -qq && \
  apt-get install -y nodejs postgresql-client && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN mkdir /app
WORKDIR /app

COPY Gemfile /app/Gemfile
COPY Gemfile.lock /app/Gemfile.lock
ENV BUNDLER_VERSION 2.0.2

RUN gem install bundler:2.0.2
RUN bundle install

COPY . /app